class BoboChoses(object):
    dresses = '[class="campaign has-text  text-plate c-4 "]:nth-of-type(4n)'
    article = 'article:nth-of-type(1n)'
    quickshop = 'div.quickshop-button '
    drop_down = '#id-slct'
    option = '#id-slct ul li:nth-of-type(2n)'
    add_cart = 'button[class="add-to-cart green large"]'
    p_name = 'p.name'
    checkout = 'a[class="to-checkout white button"]'
    delete = 'a.remove'
    cart_empty = 'Your cart is empty'
    dolce_gabbana = 'a[title="Dolce & Gabbana"]'
    filter_by = '.filter-label'
    price = 'span.lowest'
    region_change = 'a[href="/country-and-language"]'
    ru_url = 'https://ru.babyshop.com/country-and-language'
    brands = 'a[data-class="brand"]'
    postal_code = 'input[name="postalCode"]'
    city = 'input[name="city"]'
    phone = 'input[name="phoneNumber"]'
    adress = 'input[name="addressLine2"]'
    firstName = 'input[name="firstName"]'
    lastName = 'input[name="lastName"]'
    email = 'input[name="emailAddress"]'
    submit = 'button[type="submit"]'
